const { generateAnalysis } = require("./geminiService");
const { buildAnalysisPrompt } = require("../prompts/analysisPrompt");
const vectorStore = require("../vectorStore/instance");
const config = require("../config");

async function analyzeCase(caseText) {
  let similarCases = [];
  try {
    similarCases = await vectorStore.search(caseText, 5);
  } catch (error) {
    if (!config.ENABLE_FALLBACK_ANALYSIS) {
      throw error;
    }
    console.warn(
      "Vector search failed, continuing with fallback path:",
      error.message
    );
  }

  const prompt = buildAnalysisPrompt(caseText, similarCases);
  try {
    const analysis = await generateAnalysis(prompt);
    validateAnalysis(analysis);
    return analysis;
  } catch (error) {
    if (config.ENABLE_FALLBACK_ANALYSIS && isQuotaOrRateLimitError(error)) {
      return buildFallbackAnalysis(caseText, similarCases);
    }
    throw error;
  }
}

function isQuotaOrRateLimitError(error) {
  const message = (error?.message || "").toLowerCase();
  return (
    error?.status === 429 ||
    message.includes("quota") ||
    message.includes("too many requests") ||
    message.includes("rate limit")
  );
}

function buildFallbackAnalysis(caseText, similarCases) {
  const topCases = (Array.isArray(similarCases) ? similarCases : []).slice(
    0,
    3
  );
  const legalProvisions = collectLegalProvisions(topCases);

  return {
    summary: buildFallbackSummary(caseText, topCases),
    legalProvisions,
    similarCases: topCases.map((c) => ({
      caseTitle: c.metadata.caseTitle,
      year: c.metadata.year,
      caseNumber: c.metadata.caseNumber,
      similarityScore: toPercent(c.score),
      keyParallels: buildCaseParallel(c.metadata),
      decision: c.metadata.decision,
    })),
    disclaimer:
      "This analysis is generated by NyayaSahayak for informational and educational purposes only and does not constitute legal advice. Due to temporary AI quota limits, this response was produced using retrieval-based fallback logic. Please consult a qualified advocate for legal guidance specific to your situation.",
  };
}

function buildFallbackSummary(caseText, topCases) {
  const normalized = String(caseText || "")
    .replace(/\s+/g, " ")
    .trim();
  const sentenceParts = normalized
    .split(/(?<=[.!?])\s+/)
    .map((s) => s.trim())
    .filter(Boolean)
    .slice(0, 3);

  const userSummary = sentenceParts.length
    ? sentenceParts.join(" ")
    : "The submitted case describes allegations of domestic violence and seeks legal protection under applicable law.";

  if (!topCases.length) {
    return `${userSummary} Similar-case retrieval is temporarily unavailable, so this is a high-level summary pending full AI analysis.`;
  }

  const caseNames = topCases.map((c) => c.metadata.caseTitle).join("; ");
  return `${userSummary} Based on retrieved Allahabad High Court precedents (${caseNames}), the facts appear to involve domestic relationship disputes that may engage protections, residence rights, maintenance, or protective relief depending on evidence.`;
}

function collectLegalProvisions(topCases) {
  const seen = new Set();
  const provisions = [];

  for (const entry of topCases) {
    const sections = entry?.metadata?.relevantSections || [];
    for (const raw of sections) {
      const key = String(raw || "").trim();
      if (!key || seen.has(key)) continue;
      seen.add(key);

      const parts = key.split(",").map((p) => p.trim());
      const section = parts[0] || key;
      const act = parts[1] || "Relevant statute";

      provisions.push({
        section,
        act,
        relevance:
          "This provision appears repeatedly in closely matched domestic violence precedents and may be relevant depending on the proved facts.",
      });

      if (provisions.length >= 6) {
        return provisions;
      }
    }
  }

  if (!provisions.length) {
    provisions.push({
      section: "Section 3",
      act: "Protection of Women from Domestic Violence Act, 2005",
      relevance:
        "This section defines domestic violence and is typically the starting point for assessing allegations in DV proceedings.",
    });
  }

  return provisions;
}

function buildCaseParallel(metadata) {
  const facts = String(metadata?.facts || "")
    .replace(/\s+/g, " ")
    .trim();
  const shortFacts = facts.length > 220 ? `${facts.slice(0, 217)}...` : facts;
  return `This retrieved precedent contains fact patterns related to domestic conflict, and can guide comparison of allegations, evidence, and relief sought. Snapshot: ${shortFacts}`;
}

function toPercent(score) {
  if (typeof score !== "number" || Number.isNaN(score)) {
    return 0;
  }
  const bounded = Math.max(0, Math.min(1, score));
  return Math.round(bounded * 100);
}

function validateAnalysis(analysis) {
  const required = ["summary", "legalProvisions", "similarCases", "disclaimer"];
  for (const field of required) {
    if (!analysis[field]) {
      throw new Error(`Invalid LLM response: missing field "${field}"`);
    }
  }
  if (!Array.isArray(analysis.legalProvisions)) {
    throw new Error("legalProvisions must be an array");
  }
  if (!Array.isArray(analysis.similarCases)) {
    throw new Error("similarCases must be an array");
  }
}

module.exports = { analyzeCase };
